name: DigitalBank - Tests Automatises

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Execution quotidienne a 00h00 heure de Paris (23h00 UTC la veille)
    - cron: '0 23 * * 1-5'
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CONTAINER_MAIN_SERVICES: tests-chromium-mobile tests-webkit-tablet tests-firefox-desktop

jobs:

  # ═══════════════════════════════════════════════
  # Build images
  # ═══════════════════════════════════════════════
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build --parallel

      - name: Export image
        run: docker save digitalbank-tests > digitalbank-tests.tar

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: digitalbank-tests.tar
          retention-days: 1

  # ═══════════════════════════════════════════════════════════════
  # Smoke tests — push / pull request
  # ═══════════════════════════════════════════════════════════════
  tests-smoke:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load image
        run: docker load < digitalbank-tests.tar

      - name: Select random main config
        id: random
        run: |
          SERVICES=($CONTAINER_MAIN_SERVICES)
          RANDOM_SERVICE=${SERVICES[$RANDOM % ${#SERVICES[@]}]}
          echo "service=$RANDOM_SERVICE" >> $GITHUB_OUTPUT
          echo "Selected service: $RANDOM_SERVICE"

      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Run Smoke Tests
        run: docker compose run -e PYTEST_MARKERS="smoke" ${{ steps.random.outputs.service }}

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-tests-smoke
          path: digitalbank-automation/reports
          retention-days: 30

      - name: Stop containers
        if: always()
        run: docker compose down -v

  # ═══════════════════════════════════════════════════════════════
  # Regression Tests — Daily
  # ═══════════════════════════════════════════════════════════════
  tests-regression:
    if: github.event_name == 'schedule'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load image
        run: docker load < digitalbank-tests.tar

      - name: Select random main config
        id: random
        run: |
          SERVICES=($CONTAINER_MAIN_SERVICES)
          RANDOM_SERVICE=${SERVICES[$RANDOM % ${#SERVICES[@]}]}
          echo "service=$RANDOM_SERVICE" >> $GITHUB_OUTPUT
          echo "Selected service: $RANDOM_SERVICE"

      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Run Regression Tests
        run: docker compose run -e PYTEST_MARKERS="regression" ${{ steps.random.outputs.service }}

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-tests-regression
          path: digitalbank-automation/reports
          retention-days: 30

      - name: Stop containers
        if: always()
        run: docker compose down -v

  # ═══════════════════════════════════════════════════════════════
  # Complete Tests for Production-Ready Application — Manual
  # ═══════════════════════════════════════════════════════════════
  tests-production:
    if: github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        service:
          - tests-chromium-mobile
          - tests-firefox-desktop
          - tests-webkit-tablet
          - tests-chromium-desktop
          - tests-webkit-mobile
          - tests-webkit-desktop
          - tests-chromium-tablet
          - tests-firefox-mobile
          - tests-firefox-tablet

    steps:
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load image
        run: docker load < digitalbank-tests.tar

      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Run ${{ matrix.service }}
        run: docker compose run ${{ matrix.service }}

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.service }}
          path: digitalbank-automation/reports
          retention-days: 30

      - name: Stop containers
        if: always()
        run: docker compose down -v

  # ═════════════════════════════════════════════════════════════════
  # Cleanup — dernière étape du workflow pour supprimer l’artefact Docker
  # Explication : 
  # Le rebuild dans chaque job est plus rapide, on l'extrait pour la scalabilité dans le futur.
  # On prévoit plus de jobs, dont certains jobs qui peuvent s’exécuter en parallèle.
  # On va donc gagner en performance et maintenabilité au long terme.
  # Le cleanup final s’exécute toujours après l'éxecution d'au moins un des autres jobs pour libérer de l’espace.
  # ═════════════════════════════════════════════════════════════════
  cleanup:
    runs-on: ubuntu-latest
    needs:
      - tests-smoke
      - tests-regression
      - tests-production
    steps:
      - name: Delete Docker image artifact
        if: always()
        uses: geekyeggo/delete-artifact@v5
        with:
          name: docker-image